


export const SET_POSITION = 'SET_POSITION'
export const RESIZED_WINDOW = 'RESIZED_WINDOW'
export const SET_URL = 'SET_URL'
export const FOCUS_TO_ELEMENT = 'FOCUS_TO_ELEMENT'
export const SET_DIRECTION = 'SET_DIRECTION'
export const SET_SCROLL_RATE = 'SET_SCROLL_RATE'
export const SET_SCROLL_CONTROL = 'SET_SCROLL_CONTROL'

