


export const CREATE_WINDOW = 'CREATE_WINDOW'
export const REMOVE_WINDOW = 'REMOVE_WINDOW'
export const SET_SIZE = 'SET_SIZE'
export const RELOAD_PAGE = 'RELOAD_PAGE'
export const SET_WINDOW_POSITION = 'SET_WINDOW_POSITION'
export const SET_WINDOW_NAME = 'SET_WINDOW_NAME'
export const RELOAD_ALL_PAGES = 'RELOAD_ALL_PAGES'
export const FULLSCREEN_WINDOW = 'FULLSCREEN_WINDOW'
export const SET_URL_ALL_WINDOWS = 'SET_URL_ALL_WINDOWS'
export const SET_URL_MY_WINDOW = 'SET_URL_MY_WINDOW'
export const SET_CLICKED_WINDOW = 'SET_CLICKED_WINDOW'