


export const CREATE_WINDOW = 'CREATE_WINDOW'
export const REMOVE_WINDOW = 'REMOVE_WINDOW'
export const SET_SIZE = 'SET_SIZE'
export const RELOAD_PAGE = 'RELOAD_PAGE'
export const SET_WINDOW_POSITION = 'SET_WINDOW_POSITION'
